[profile.default]
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
bytecode_hash = "none"
cbor_metadata = false

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
